project:
    Name: example-workspace
    Description: Example project for publishing to PyPI

publishers:
    name: providers
    url: https://dist.apache.org/repos/dist/release/airflow/
    path: "airflow/providers/"
    version_pattern: '^(.*?)-(rc\d+-)?\d+'
    extensions:
      - .tar.gz
      - .tar.gz.asc
      - .tar.gz.sha512
      - -py3-none-any.whl
      - -py3-none-any.whl.asc
      - -py3-none-any.whl.sha512
    rules:
      svn-check:
          name: "SVN Check"
          type: "svn"
          enabled: "true"
      checksum-check:
          name: "SHA512 Check"
          type: "512"
          enabled: "true"
          script: "/home/runner/work/example-workspace/example-workspace/scripts/checksum_check.sh"

