name: Release Publisher
on:
  workflow_dispatch:

jobs:
  rc-release:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Validate RC Release
       uses: gopidesupavan/gh-svn-pypi-publisher@basic-feat
       with:
         publish-config: 'publish-config.yml'
